### ISSUE TITLE
Bug inscription

### ISSUE THREAD

**Issue by Swept5743** [GeanyDuMal/AEDI_Support#3]
Bonjour j'ai un soucis pour l'inscription , quand je souhaite m'inscrire je rentre toutes mes données et quand je clique sur inscription ca me met "Merci de vérifier votre saisie"
![image](https://user-images.githubusercontent.com/114573610/192743208-a93e369c-381c-4407-84a0-3d50473c8554.png)

**Comment by Spl4shh** [comment]
@Swept5743 Pourrait on avoir un screen des infos que tu saisis avant de cliquer ?

**Comment by Swept5743** [comment]
![image](https://user-images.githubusercontent.com/114573610/192823943-7517b05c-0896-4a25-b7ab-2e4ddcbd0c1e.png)

**Comment by Spl4shh** [comment]
@Swept5743 As tu bien respecté les critères de mot de passe ?

**Comment by Swept5743** [comment]
oui appart si un @ n'est pas considère comme un caractère spécial

**Comment by Spl4shh** [comment]
Effectivement, le @ ne passe pas.
Je le rajoute dans la soirée.
Je mettrais un message pour confirmer que c'est ok

**Comment by Swept5743** [comment]
d'accord pas de problème

**Comment by Spl4shh** [comment]
Erreur corrigé, mise en prod effectué.
Je clôture le ticket

**Comment by Spl4shh** [comment]
Error 500, a verifier la provenance

**Comment by Spl4shh** [comment]
Erreur lié à un bug sous jacent.
Corrigé et testé
