### ISSUE TITLE
carte bancaire

### ISSUE THREAD

**Issue by Ozraam** [GeanyDuMal/AEDI_Support#4]
serait t'il possible de donner le prix avec les 5 cent en plus avec la carte par 2€

**Comment by Spl4shh** [comment]
Tu souhaite d'avoir affiché le prix avec directement les 5cts en plus compris par tranche de 2€ ou tu veux avoir inscrit "x€ + x cts" ?

**Comment by Ozraam** [comment]
+x cts c'est bien

**Comment by Spl4shh** [comment]
Okay, je créé le ticket, ce sera fait assez vite

**Comment by Spl4shh** [comment]
@Ozraam 
C'est en ligne
