### ISSUE TITLE
Page de confirmation de suppression de compte

### ISSUE THREAD

**Issue by Ozraam** [GeanyDuMal/AEDI_Support#6]
Lors de la suppression d'un compte, la page de validation de suppression affiche uniquement "true"

**Comment by Spl4shh** [comment]
Vu, sera effectué prochainement
A confirmer mais très certainement dans la prochaine version car n'est pas bloquant

**Comment by Spl4shh** [comment]
Corrigé, sera présent dans la prochaine version
